#!/usr/bin/env python3
"""
generate_strings.py

Converts the master localization_hub.json dictionary into native
iOS (.strings) and Android (.xml) resource files.

This script is run automatically by the GitHub Action defined in
.github/workflows/generate-localization.yml whenever localization_hub.json
changes on main. Mobile developers should never need to run this locally -
see README.md for the build-time sync scripts that consume the /outputs
files this script produces.

Usage:
    python3 scripts/generate_strings.py
"""

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_FILE = REPO_ROOT / "localization_hub.json"
OUTPUT_DIR = REPO_ROOT / "outputs"


def to_snake_case(name: str) -> str:
    """Convert a PascalCase screen name like 'PurchaseTicketScreen' into
    a short snake_case prefix like 'purchase_ticket'."""
    name = name[:-6] if name.endswith("Screen") else name
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def flatten(data: dict) -> dict:
    """Flatten the nested {Screen: {key: {ar, en}}} structure into a single
    dict of {flat_key: {ar, en}}, validating that both languages are present."""
    flat = {}
    errors = []

    for screen, entries in data.items():
        prefix = to_snake_case(screen)
        for key, value in entries.items():
            flat_key = f"{prefix}_{key}"

            if "ar" not in value or "en" not in value:
                errors.append(f"{screen}.{key} is missing 'ar' or 'en'")
                continue

            if flat_key in flat:
                errors.append(f"Duplicate generated key '{flat_key}' "
                              f"(collision between screens)")
                continue

            flat[flat_key] = value

    if errors:
        print("Validation failed:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        sys.exit(1)

    return flat


def escape_ios(value: str) -> str:
    """Escape a string for use inside an iOS .strings file."""
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def escape_android(value: str) -> str:
    """Escape a string for use inside an Android strings.xml file."""
    value = (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace("'", "\\'")
        .replace('"', "&quot;")
        .replace("\n", "\\n")
    )
    return value


def write_ios_strings(flat: dict, lang: str, out_path: Path) -> None:
    lines = [
        "/* Auto-generated by scripts/generate_strings.py - do not edit by hand. */",
        "",
    ]
    for key in sorted(flat):
        value = escape_ios(flat[key][lang])
        lines.append(f'"{key}" = "{value}";')
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_android_xml(flat: dict, lang: str, out_path: Path) -> None:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Auto-generated by scripts/generate_strings.py - do not edit by hand. -->",
        "<resources>",
    ]
    for key in sorted(flat):
        value = escape_android(flat[key][lang])
        lines.append(f'    <string name="{key}">{value}</string>')
    lines.append("</resources>")
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if not SOURCE_FILE.exists():
        print(f"Source file not found: {SOURCE_FILE}", file=sys.stderr)
        sys.exit(1)

    data = json.loads(SOURCE_FILE.read_text(encoding="utf-8"))
    flat = flatten(data)

    OUTPUT_DIR.mkdir(exist_ok=True)

    write_ios_strings(flat, "en", OUTPUT_DIR / "en.strings")
    write_ios_strings(flat, "ar", OUTPUT_DIR / "ar.strings")
    write_android_xml(flat, "en", OUTPUT_DIR / "strings-en.xml")
    write_android_xml(flat, "ar", OUTPUT_DIR / "strings-ar.xml")

    print(f"Generated {len(flat)} keys across 4 files in {OUTPUT_DIR}/")


if __name__ == "__main__":
    main()
